import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Besley:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <nav className="absolute top-0 w-full mx-auto p-5">
				<div className="mx-auto">
					<div className="flex">
						<img src="/images/lOGO-GRUV-1.png" alt="" />
					</div>
					<div id="social-menu" className="flex"></div>
			</div>
			</nav>
			<section id="hero" className="bg-black p-10 h-screen content-center flex flex-wrap">
				<div class="container mx-auto">
					<div className="w-1/2">
						<p className="font-besley text-gray-400 text-sm flex-none mb-4">GRUV</p>
						<p class="font-besley text-white flex-none text-4xl leading-tight font-extralight">Veja como a Gruv vai ajudar você a conquistar e fidelizar clientes e parceiros comerciais!</p>
						<button className="bg-orange-gruv hover:bg-yellow-700	rounded-full py-3 px-14 text-white text-sm mt-4">FALE COM UM GRUVER</button>
					</div>
				</div>
			</section>
			<section className="bg-black py-20 h-auto content-center flex flex-wrap">
				<div class="container mx-auto grid grid-cols-2 grid-flow-col gap-10">
					<div className="">
						<img src="/images/Gruv-Desafiar-1.png" alt="" />
						<p className="text-white font-montserrat font-light text-2xl my-10">Com base em estratégias de conteúdo, compartilhamento, geração de leads e criação de sites, desafiamos o normal entregando resultados incríveis para a sua empresa!</p>
						<p className="text-white font-montserrat font-light text-2xl my-10">Você acredita que juntos podemos destacar sua marca na internet? Descubra nossos serviços de Digital e fale com um Gruver:</p>
						<button className="bg-orange-gruv hover:bg-yellow-700	rounded-full py-3 px-14 text-white text-sm mt-4">FALE COM UM GRUVER</button>
					</div>
					<div class="flex m-auto">
						<img src="/images/carrossel 1.png" alt="" />
					</div>	
				</div>
			</section>
			<section className="bg-gray-gruv py-20 h-auto content-center flex flex-wrap">
				<div class="w-2/3 mx-auto grid grid-cols-4 grid-flow-col gap-20">
					<div className="">
						<img src="/images/pointer 1.png" alt="" />
						<p className="text-white font-montserrat font-light text-lg font-bold">Plan the Way</p>
						<ul class="text-gray-500 text-sm">
							<li className="my-5">Estudo e criação de Personas;</li>
							<li className="my-5">Definição de caminho criativo;</li>
							<li className="my-5">Desenvolvimento de manifesto da marca;</li>
							<li className="my-5">Estruturação de campanha de mídia.</li>
						</ul>
					</div>
					<div className="">
						<img src="/images/post-to-share 1.png" alt="" />
						<p className="text-white font-montserrat font-light text-lg font-bold">Post to share</p>
						<ul class="text-gray-500 text-sm">
							<li className="my-5">Criação de uma ideia Compartilhável;</li>
							<li className="my-5">Desenvolvimento de calendário de conteúdo para redes sociais;</li>
							<li className="my-5">Desenvolvimento de criativos para campanhas;</li>
							<li className="my-5">Análise de resultados;</li>
							<li className="my-5">Insights e melhorias.</li>
						</ul>
					</div>
					<div className="">
						<img src="/images/leads 1.png" alt="" />
						<p className="text-white font-montserrat font-light text-lg font-bold">Leads magnet</p>
						<ul class="text-gray-500 text-sm">
							<li className="my-5">Definir oferta;</li>
							<li className="my-5">Segmentação inteligente de base;</li>
							<li className="my-5">Criação de páginas de conversão;</li>
							<li className="my-5">Campanhas de e-mail marketing;</li>
							<li className="my-5">Estratégia de conteúdo automatizado</li>
							<li className="my-5">Definição de oportunidades de vendas;</li>
							<li className="my-5">Análise de resultados;</li>
							<li className="my-5">Insights e melhorias.</li>
						</ul>
					</div>
					<div className="">
						<img src="/images/websites 1.png" alt="" />
						<p className="text-white font-montserrat font-light text-lg font-bold">Awesome sites</p>
						<ul class="text-gray-500 text-sm">
							<li className="my-5">Você dono do site;</li>
							<li className="my-5">Hospedagem na Amazon Web Services;</li>
							<li className="my-5">Você tem acesso a edição;</li>
							<li className="my-5">Você tem acesso ao Painel;</li>
							<li className="my-5">Acesso as principais métricas de forma descomplicada.</li>
						</ul>
					</div>	
				</div>
				<button className="bg-orange-gruv hover:bg-yellow-700	rounded-full py-3 px-14 text-white text-sm mt-4 mx-auto w-1/2">POTENCIALIZE O DIGITAL DA SUA EMPRESA</button>
			</section>
			<section className="bg-gray-50 py-20 h-auto content-center flex flex-wrap">
				<div class="w-2/3 mx-auto grid grid-cols-3 grid-flow-col gap-10">
					<div className="text-center bg-white p-10 rounded-lg shadow-sm">
						<img src="/images/em-tempo1.png" className="mx-auto" alt="" />
						<p className="font-montserrat font-light text-lg font-bold">+5</p>
						<p className="text-sm">Anos de experiência no mercado</p>
					</div>
					<div className="text-center bg-white p-10 rounded-lg shadow-sm">
						<img src="/images/em-tempo1.png" className="mx-auto" alt="" />
						<p className="font-montserrat font-light text-lg font-bold">+5</p>
						<p className="text-sm">Anos de experiência no mercado</p>
					</div>	
					<div className="text-center bg-white p-10 rounded-lg shadow-sm">
						<img src="/images/em-tempo1.png" className="mx-auto" alt="" />
						<p className="font-montserrat font-light text-lg font-bold">+5</p>
						<p className="text-sm">Anos de experiência no mercado</p>
					</div>	
				</div>
			</section>
			<section className="bg-white py-10 h-auto content-center flex flex-wrap">
				<div class="container mx-auto grid grid-cols-2 grid-flow-col gap-10">
					<div className="">
						<h1 className="font-besley text-5xl	my-10 w-4/5">O método Gruv para desafiar o normal</h1>
						<p className="font-montserrat font-light text-sm my-10">Utilizamos a metodologia Double Diamond, na qual criamos um mapa de como a equipe pode atuar na resolução de problemas ou criação de produtos, serviços e processos. Nessa metodologia, incentivamos o brainstorm no desenvolvimento de ideias diferentes para um único problema, gerando diferenciação em nossas ações no dia a dia.</p>
					</div>
					<div class="flex m-auto">
						<img src="/images/graphic-01.png" alt="" />
					</div>	
				</div>
			</section>
			<section className="bg-white py-10 h-auto content-center text-center flex flex-wrap">
				<div class="container mx-auto text-center">
					<h1 className="font-besley text-5xl	my-5">NOSSOS CLIENTES</h1>
						<div className="border-t-2 w-1/2 mx-auto"></div>
						<p className="font-montserrat font-light text-sm my-3">Marcas que acreditam no que a gente acredita</p>
					<div className="grid grid-cols-5 gap-4">
						<div>
							<img src="/images/clientes/01.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/02.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/03.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/04.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/05.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/06.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/07.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/08.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/09.png" alt="" />
						</div>
						<div>
							<img src="/images/clientes/10.png" alt="" />
						</div>
					</div>
				</div>
			</section>
			<section id="form">
				<div class="container">
					<div role="main" id="formulario-lp-digital-9fa49ac25a5a9e347b78"></div><script type="text/javascript" src="https://d335luupugsy2.cloudfront.net/js/rdstation-forms/stable/rdstation-forms.min.js"></script><script type="text/javascript"> new RDStationForms('formulario-lp-digital-9fa49ac25a5a9e347b78', 'UA-84554307-2').createForm();</script>
				</div>
			</section>

      <footer className="bg-black py-10">
				<div className="container mx-auto">
					<div className="grid grid-cols-4 grid-flow-col gap-20">
						<div>
							<h1 class="text-white mb-5 font-besley text-lg">Fale com a gente</h1>
							<ul class="text-sm text-white">
								<li className="">contato@gruv.com.br</li>
								<li className="font-bold">Brasília</li>
								<li className="font-bold">São Paulo</li>
							</ul>
							<ul class="text-sm text-white  mt-10">
								<li className="">Ouvidoria</li>
								<li className="">Politica de Privacidade</li>
							</ul>
						</div>
						<div>
							<h1 class="text-white mb-5 font-besley text-lg">Carreira</h1>
							<ul class="text-sm text-white">
								<li className="">Oportunidades</li>
								<li className="">Gruvers</li>
								<li className="">Trabalhando na Gruv</li>
							</ul>
							<ul class="text-sm text-white  mt-10">
								<li className="">O que procuramos</li>
							</ul>
						</div>
						<div>
							<h1 class="text-white mb-5 font-besley text-lg">Comunidade</h1>
							<ul class="text-sm text-white">
								<li className="">Gruv Insight</li>
								<li className="">Gruvcast</li>
							</ul>
					</div>
					<div>
						<h1 class="text-white mb-5 font-besley text-lg">Comunidade</h1>
						<ul class="text-sm text-white">
							<li className="">Linked In</li>
							<li className="">Instagram</li>
							<li className="">Facebook</li>
							<li className="">Twitter</li>
						</ul>
					</div>
				</div>
				<div className="w-full mt-20">
					<img src="/images/lOGO-GRUV-1.png" alt="" class="mx-auto"/>
				</div>
				</div>
      </footer>
    </div>
  )
}
